PHPコース練習課題2(ソートアルゴリズム)
masayoshixxx/codegym-php pull request #2
Opened 2021-05-05 12:38 UTC by masayoshixxx

2021-05-10 11:40 UTC, disneyLadySango reviewed
@masayoshixxx 
基本的にはOKですが、コードの整形が必要です！

また１点チャレンジしてみて欲しいことをコメントしてみたのでこちらぜひ考えてみてください

2021-05-10 11:40 UTC, disneyLadySango commented on html/php-pre-challenge2/index.php
> +$length=count($array);
[nits]
細かいところではあるんですが、
`$length = count($array);`
といった感じで` =` の両サイドは空白を開けてください

2021-05-10 11:40 UTC, disneyLadySango commented on html/php-pre-challenge2/index.php
> +for($i=0;$i<$length-1;$i++){
[should]
こちらも同様ですね、自動整形されると勝手に変換されるかもですが、
`for ($i = 0; $i < $length - 1; $i++) {`
といった感じできちんとスペースを入れましょう

2021-05-10 11:40 UTC, disneyLadySango commented on html/php-pre-challenge2/index.php
> +    for($j=0;$j<$length-1;$j++){
[challenge]
こちらチャレンジしてみてください！
せっかく`count($array)`という形で$lengthに対する性能改善をしていただいたのでぜひこちらもチャレンジしてみてください。

前提
- 今回のソートは大きい数字から数が決まっていく

やって欲しいこと
- for文を実行する回数を減らしてバブルソートを実施して欲しい

````
〜ソートの解説〜

[3, 4, 2, 1] という数字があったときに

最初の$iが0の時に実行される判定処理は以下のようになります

1回目のL9の if($array[$j]>$array[$j+1]){ を実行すると・・・
  3 > 4 -> ソートされない
2回目のL9を実行すると
  4 > 2 -> ソートされる [3, 2, 4, 1]
3回目のL9を実行すると
  4 > 1 -> ソートされる [3, 2, 1, 4]

つまり今回のソートで何が起きたかというと、
【一番大きい数字が一番後ろにきました】
ということは「4」という数字の順番は決まったので
$i = 1の時や$i = 2の時に一番大きい数字を再度調査する必要がないということになります。

なので $i = 1の時の処理は「4」以外を調査すれば良いので以下のようになるはずです
1回目のL9を実行すると
  3 > 2 -> ソートする [2, 3, 1, 4]
2回目のL9を実行すると
  3 > 2 -> ソートする[2, 1, 3, 4]
だけで良いはずです

$i = 2に至っては・・・もうわかりますよね？

こうすることでfor文の実行が減り性能が上がります
では今回文字での説明だったのでこれをコードに置き換えてみるとどうなるかぜひ考えてみてください
````

この話が理解できるならバブルソートとはなんぞや！というのがきちんと理解できている証拠かと思います
頑張って実装してみましょう！

2021-05-10 13:15 UTC, masayoshixxx commented on html/php-pre-challenge2/index.php
> +    for($j=0;$j<$length-1;$j++){
チャレンジ課題ありがとうございます。
for文の中の方の[$length - 1]を[$length - $i]に変更することで
実行回数が減ると考えました。
計算回数は表示されないので合っているか事前に確かめられていないですが
添削のほどよろしくお願いいたします。

2021-05-11 08:25 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +    for($j=0;$j<$length-1;$j++){
> 計算回数は表示されないので合っているか事前に確かめられていないですが

こちらのコメントは見過ごせないですね～。
カウンタを設置することで簡単に計算回数を把握することができます。
※PRを修正することはありません。

```php
<?php
$array = explode(',', $_GET['array']);

// 修正はここから
$length = count($array);

// 比較回数
$cnt = 0;

for ($i = 0; $i < $length - 1; $i++) {
  for ($j = 1; $j < $length - $i; $j++) {
    $cnt++;
    if ($array[$j] < $array[$j - 1]) {
      $tmp = $array[$j];
      $array[$j] = $array[$j - 1];
      $array[$j - 1] = $tmp;
    }
  }
}
// 修正はここまで

echo "<pre>";
print_r($array);
print_r("比較回数: $cnt 回");
echo "</pre>";
```

2021-05-11 08:28 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +  }
インデントの深さがずれていますね!!!!!

開発の現場ではソースコードが長くなってしまいがちで、それだけにインデントのずれはレビューで必ず指摘されます(インデントがずれた閉じカッコを見つけるとめまいがします)。

字下げの深さ4と2が混在していることが原因ですね。PHP Intelephense で自動整形しましょう。

2021-05-11 08:39 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +  }
```suggestion
for ($i = 0; $i < $length - 1; $i++) {
  for ($j = 1; $j < $length - $i; $j++) {
    if ($array[$j] < $array[$j - 1]) {
      $tmp = $array[$j];
      $array[$j] = $array[$j - 1];
      $array[$j - 1] = $tmp;
    }
  }
}
```

2021-05-11 08:41 UTC, Yuzunoha requested changes
動作結果はOKでした！チャレンジも達成していると思います(比較回数の把握に関してコメントしているのでそちらもご確認ください)。

コードの整形に関してコメントしました。

2021-05-11 09:58 UTC, masayoshixxx commented on html/php-pre-challenge2/index.php
> +    for($j=0;$j<$length-1;$j++){
比較回数そんなに数行でできたんですね。。
できるとしてもHTMLチェッカーのようなサイトかと思っていましたが、
いずれにせよ一手間調べてみればよかったです。（反省）

2021-05-11 11:10 UTC, disneyLadySango approved these changes
@masayoshixxx 

ご対応ありがとうございます！課題ばっちりですね！！！LGTMです！

挑戦して欲しいところもばっちり挑戦してくれていて、
ソートアルゴリズムの理解度が増しているのかなと思いました！
もし分からないところがあればぜひ講師部屋で聞いてもらえればと思います！

2021-05-29 05:40 UTC, merged